### ISSUE TITLE
Wrap Quill and add value property

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-rich-text-editor#2]
[Plans here](https://docs.google.com/document/d/1ApZJ2I7URhyz9LCTrUP7z4a1ThILQgdeS0v-5Y9c1Cg/edit#heading=h.tmzrzuvi9lcs)

- `value` should represent the Quill's [Delta](https://quilljs.com/docs/delta/)

**Comment by web-padawan** [comment]
There is a pending PR introducing shadow DOM support: quilljs/quill#1805

I'm in favour of creating our own fork for now, and re-using the work from there.

**Comment by web-padawan** [comment]
Submitted a PR rebased on top of 1.3.6 release: quilljs/quill#2337

Tests are failing in Safari because not implemented `getSelection()` API.
Potential fix would be using https://github.com/GoogleChromeLabs/shadow-selection-polyfill

**Comment by web-padawan** [comment]
### Sort summary

Only Chrome supports `getSelection()` on the Shadow Root. Neither Firefox 63 beta, nor Safari have it enabled. We need to invest some time in development of our own polyfill to make it work.

### Long Story 

Original issue is being discussed here: w3c/webcomponents#79
There is no final agreement around it yet, although we might hear some news in the end of October: https://github.com/w3c/webcomponents/issues/763#issuecomment-426514447

There is an unofficial polyfill by one guy from Google but in only covers part of functionality:
https://github.com/GoogleChromeLabs/shadow-selection-polyfill

Especially, it does not polyfill the whole `getSelection()` properly, but rather `getSelection().getRangeAt(0)` which is something but we need more methods present there, at least `Selection.removeAllRanges()` and `Selection.addRange()`

This issue is not only about the QuIll itself, as it will also affect e.g. Trix, see basecamp/trix#403
Basically, any editor relying on `window.getSelection()` or `document.getSelection()` which is the same, will be affected by that issue when placed inside of the shadow root.

For instance, `ace-editor` (which is not a WYSIWYG) doesn't care: https://github.com/ajaxorg/ace/issues/3590#issuecomment-369662471

### Solution options 

1. it might be that Google has some kind of working polyfill internally, it might make sense to ask (at least from what I understand they are upgrading from Polymer 1 now and should face this issue, too)

2. implement our own polyfill, e.g. based on https://github.com/timdown/rangy/wiki/Rangy-Selection
This would mean quite extra work and testing effort. Then we would have to somehow integrate it into the Quill editor, which is a separate question (once we have a polyfill, should not be too complex).

**Comment by platosha** [comment]
Could “Make Quill work on light DOM” be an option?

**Comment by web-padawan** [comment]
@platosha the users would be still placing Quill inside of the some shadow root (either view or app-shell components), and in Safari the `window.getSelection()` will no longer report correct nodes.

**Comment by web-padawan** [comment]
Early prototype pushed as https://github.com/vaadin/vaadin-rich-text-editor/tree/proto/wrap-quill

## Problems identified:

1. shadow selection polyfill only works partially in Safari. Example: 
  - type some text
  - select it
  - choose "Header" in the formatting select
  - nothing happens

This line gets empty `range` although works in Chrome: https://github.com/web-padawan/quill/blob/303d73fdd4bdf50a678877caf24927311305d91a/modules/toolbar.js#L87

2. shadow selection polyfill produces lots of log output in Safari while cursor is inside of the editor, causing a performance bottleneck and even handing browser tab at some point (investigating)

3. ShadyCSS scoping is not fully applied to select in Firefox:

![screen shot 2018-10-04 at 9 31 32](https://user-images.githubusercontent.com/10589913/46456657-517f3080-c7b8-11e8-9a78-0ac0077d2f25.png)

**Comment by web-padawan** [comment]
Update:

1. Shadow selection polyfill must be only invoked in Safari, it will break in IE11, Edge and Firefox

2. Shadow selection polyfill does not work properly with Quill out of the box because of this line: https://github.com/quilljs/quill/blob/96e38e92637b75b907579d0cc1b201920aebe38c/core/selection.js#L32

See the listener in the polyfill where `setTimeout` is also used and the timeout is `0`:     https://github.com/GoogleChromeLabs/shadow-selection-polyfill/blob/9eff233c765a685bbf488b2f8eba0d3d75f44cbd/shadow.js#L74

**Comment by aadamsx** [comment]
Are there plans to wrap the ckeditor too?  I've used both, and ckeditor has always been full featured.

**Comment by web-padawan** [comment]
@aadamsx we have decided to build initial version on top of Quill. In the future we might consider changing the internal implementation based e.g. on customer requests, but no such plans for now.
