### ISSUE TITLE
Setter for htmlValue

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-rich-text-editor#68]
Add API for setting the `htmlValue` programmatically.
The new API `dangerouslySetHtmlValue` should empty the container and use Quill's `dangerouslyPasteHTML` to populate it with the new value.

**Comment by heruan** [comment]
Definitely needed! The user can already paste HTML into the editor and the results are good, but this should be able to be done programmatically too from both the WC and Flow integration.

**Comment by heruan** [comment]
After nearly a week working with Vaadin's RTE (a.k.a. Quill) and Delta, I've come out really frustrated. Delta *is* a good format, but it lacks libraries to handle it: there are Node.js packages to convert Delta to/from HTML, but they just fake a DOM and use a Quill instance on it; if you're on Java backend, the only workaround I've found was to use Selenium's `ChromeDriver` to load Quill there and do the conversions. Plus, ATM the Quill project seems pretty much abandoned.

Since we're about launching an app heavily based on text editing (based on V14), I'd really like to hear a plan on Vaadin's RTE!

**Comment by Peppe** [comment]
Yes, Quill has maybe come to a standstill. Still, the component itself feels good to me and I think we can work with it, even if the pace of Quill isn't stunning.

I see that we are missing two important pieces.
 * A server-side tool to convert Delta into HTML. This is needed so that you can render RTE content outside of an editor, without having to maintain a delta and HTML version of each text in your database.
 * a `setHTML()` method to give in HTML, as per this ticket.

We don't have any defined plans about RTE specifically. I would like to hear others' thoughts on how we should solve these.
